# Generated by Django 2.0.5 on 2018-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20180528_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
