# Generated by Django 2.0.5 on 2018-05-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_evento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horario_event',
            field=models.TimeField(null=True),
        ),
    ]
