# Generated by Django 2.0.5 on 2018-05-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20180530_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horario_event',
            field=models.DateTimeField(null=True),
        ),
    ]
