# Generated by Django 2.0.5 on 2018-05-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='status',
        ),
        migrations.AddField(
            model_name='noticia',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
