# Generated by Django 2.0.5 on 2018-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('core', '0002_auto_20180527_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='eventos',
            field=models.ManyToManyField(to='eventos.Evento'),
        ),
    ]
