# Generated by Django 2.0.5 on 2018-05-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_noticia_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
